### ISSUE TITLE
Schedule does not respect epsilon

### ISSUE THREAD

**Issue by IreneBrugnara** [plaans/aries#127]
The attached scheduling problem modeled in unified-planning and solved by Aries produces a schedule which is unexpected since it does not respect the problem's parameter epsilon equal to 1.

[scheduling_problem.txt](https://github.com/plaans/aries/files/14050447/scheduling_problem.txt)

**Comment by arbimo** [comment]
Under the discrete time semantics, the epsilon gives the time elapsed between two epochs and is here respected.

What may be surprising to you is that two increase/decrease effects are allowed to overlap (not mutex) as long as the modified resource stays within its bounds after the effects. This is not perfectly compliant with the no-moving-target rule (at least is some of its interpretations) but is necessary to accurately represent many scheduling problems.

Note that you have always the ability to release the resource one time step later if that is what you want your model to do.

PS: the deadline is constraint is irrelevant to the discussion. If you were to minimize the makespan, you would get the same behavior.

**Comment by IreneBrugnara** [comment]
I understand, thank you for the clarification.
