### ISSUE TITLE
[up] Unknown options for Fuser - MacOS

### ISSUE THREAD

**Issue by franklinselva** [plaans/aries#81]
Running UP Aries on MacOS returns the following:

```
Unknown option: k
Unknown option: n
fuser: [-cfu] file ...
        -c      file is treated as a mount point
        -f      the report is only for the named files
        -u      print username of pid in parenthesis
```

It looks like Fuser usage is valid on Linux but fails on MacOS. I am not sure if this warning leaves the Aries GRPC port open in some systems.

**Comment by arbimo** [comment]
Hi Selva,

You might be using an outdated version. You might want to have a look at the new implementation of `unified_planning.Aries`, that has quite radically evolved recently:

https://github.com/plaans/aries/blob/master/planning/unified/plugin/up_aries/solver.py

**Comment by franklinselva** [comment]
Thanks. I don’t see the problem now.
